build/rhombus.js
src/rhombus.song.js

Yep. Import/Export is working with the music app, as far as I can tell.

More song refactoring. Fixed some stupid bugs.

---

build/rhombus.js
src/rhombus.edit.js
src/rhombus.header.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.time.js

Quite a few changes to note scheduling. The issue with notes hanging after stop seems to be fixed. Various other "fixes" and "improvements."

Scheduler Changes

---

build/rhombus.js
gulpfile.js
src/rhombus.edit.js
src/rhombus.header.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js

I've added some basic skeleton code to support tracks. Note-off scheduling has been reworked a bit. Various other changes... see details in the commit messages.

Track Skeleton Stuff

---

build/rhombus.js
src/rhombus.edit.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js

Still in the thick of adding multi-track playback. The implemenation is pretty half-baked, but it doesn't seem to have broken anything.

Multi-Track Support (continued)

---

build/rhombus.js
demos/timebase-demo.html
src/rhombus.header.js
src/rhombus.instrument.js

Added the actual instrument interface (addInstrument, removeInstrument, etc.).
Also added the generic parameter interface that maps normalized parameters to Tone values on the Tone provided instruments.

Instrument interface additions

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.song.js

Should be all in there, I tested it a bit. Instrument types and current parameters will be exported/imported successfully.
Also fixed some issues with serialization where ```_id``` values would sometimes become strings after importing.

Instrument serialization

---

build/rhombus.js
demos/timebase-demo.html
src/rhombus.edit.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js

I've added a new run-time Note type called RtNote that keeps track of the pitch and the start and end times (in seconds, relative to the elapsed time since playback started) to make it easier to keep track of playing notes and schedule note-off events.

Scheduler Modifications & Other Tweaks

---

build/rhombus.js
src/rhombus.header.js
src/rhombus.song.js
src/rhombus.track.js

Added a run-time ID for playing notes and made a few tweaks to Playlist.

Run-Time ID and Playlist Updates

---

build/rhombus.js
src/rhombus.effect.js
src/rhombus.instrument.js
src/rhombus.track.js
src/rhombus.util.js

I added the 'flat' parameter interface for instruments and effects.
You can also get the name of each parameter.
I also made it so that "_playingNotes" isn't included in tracks when the song is exported.

Added 'flat' parameter interface

---

build/rhombus.js
src/rhombus.pattern.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js

Various changes to the scheduler, pattern editing, and name accessor functions.

Rhombus Tweaks

---

build/rhombus.js
src/rhombus.edit.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js

I've begun the process of moving from a global Instrument to multiple instruments. All tracks are currently 'routed' to all instruments, but multiple instruments should be supported in theory. This is only the first step.

Instrument Routing Changes

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.sampler.js
src/rhombus.util.js

Added function to set instrument parameters by name

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.time.js

Bone-headed use of the normalized parameter interface. I'm sure we can do much better, but this might be an okay first approximation.

Parameter Interface

---

build/rhombus.js
src/rhombus.instrument.js

Like your function, but for set-by-name functionality.

Added parameter by name functionality to global setter

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.sampler.js
src/rhombus.util.js

Now you can get strings in the UI that show the value of a parameter

Added display string stuff

---

build/rhombus.js
src/rhombus.header.js
src/rhombus.instrument.js
src/rhombus.song.js
src/rhombus.time.js

This is mostly a quick update to fix a few small bugs in the pull request #50. I also added a NaN check for BPM values and logic to rescale the end time of playing notes when the tempo changes during playback.

Bug Fixes and BPM Tweaks

---

build/rhombus.js
src/rhombus.edit.js
src/rhombus.header.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js
src/rhombus.util.js

I've added a function to split a source pattern into two destination patterns. I've also implemented track muting and soloing.

Pattern Split Function / Track Mute / Track Solo

---

build/rhombus.js
demos/timebase-demo.html
src/rhombus.edit.js
src/rhombus.header.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.sampler.js
src/rhombus.song.js
src/rhombus.track.js
src/rhombus.util.js

Added lots of undo

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.song.js
src/rhombus.util.js

Fixed some small bugs

---

build/rhombus.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js

Added a few functions to work with playlist items. It's all in the commits.

Playlist Item Stuff

---

build/rhombus.js
gulpfile.js
src/rhombus.effect.js
src/rhombus.graph.js
src/rhombus.instrument.js
src/rhombus.master.js
src/rhombus.sampler.js
src/rhombus.song.js

There are functions for connecting nodes in the audio graph, plus a master node that everything should route to for output.

Added basic effect graph functionality

---

build/rhombus.js
demos/Tone.js
src/rhombus.edit.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.sampler.js
src/rhombus.song.js
src/rhombus.time.js
src/rhombus.track.js
src/rhombus.util.js

I have added provisional support for note velocity. Instruments don't respond to velocity, for whatever reason.
I also added a color properties to patterns. New patterns are assigned a random color.

Note Velocity & Pattern Color

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.sampler.js
src/rhombus.util.js

Added functions to get parameter values.
The added functions are pretty clearly visible in the diff below, the rhombus.instrument.js file. Still need to get this sampler/instrument refactor stuff worked out (hopefully before we launch on Sunday).

Added changes to get parameter values

---

build/rhombus.js
src/rhombus.instrument.js
src/rhombus.pattern.js
src/rhombus.sampler.js
src/rhombus.time.js
src/rhombus.util.js

I have refined the loop override behavior to better handle manually setting the playback position when loop is enabled.
I also changed some of the parameter mappings, especially in the envelopes (where sustain was treated as a time value, instead of a level).

Loop Override Enhancements and Parameter Mapping Tweaks
